### ISSUE TITLE
No signature of method: com.dorongold.gradle.tasktree.TaskTreeTask$_render_closure5.doCall() 

### ISSUE THREAD

**Issue by martinbonnin** [dorongold/gradle-task-tree#24]
This happens on an Android project. It sounds like a jetifier/androidx issue but I'm really not sure....

    > No signature of method: com.dorongold.gradle.tasktree.TaskTreeTask$_render_closure5.doCall() is applicable for argument types: (org.gradle.api.internal.artifacts.transform.TransformInfo$ChainedTransformInfo, java.lang.Integer) values: [IdentityTransform, 0]
    Possible solutions: doCall(org.gradle.execution.taskgraph.TaskInfo, int), findAll(), findAll()

**Comment by martinbonnin** [comment]
`> No signature of method: com.dorongold.gradle.tasktree.TaskTreeTask$_render_closure5.doCall() is applicable for argument types: (org.gradle.api.internal.artifacts.transform.TransformInfo$ChainedTransformInfo, java.lang.Integer) values: [IdentityTransform, 0]
  Possible solutions: doCall(org.gradle.execution.taskgraph.TaskInfo, int), findAll(), findAll()
`

**Comment by dorongold** [comment]
Which version of Gradle are you running?
Also, could you provide the full stacktrace by running `gradle build taskTree --stacktrace` ?

**Comment by martinbonnin** [comment]
I'm using gradle 4.9 and the gradle wrapper. My command looks like: `./gradlew :app:assembleAlphaDebug taskTree --stacktrace`


    > Task :XXX:taskTree FAILED
    
    ------------------------------------------------------------
    Project :XXX
    ------------------------------------------------------------
    
    :XXX:assembleInternal_alphaDebug
    +--- :XXX:compileInternal_alphaDebugSources
    |    +--- :XXX:compileInternal_alphaDebugJavaWithJavac
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':XXX:taskTree'.
    > No such property: task for class: org.gradle.api.internal.artifacts.transform.TransformInfo$ChainedTransformInfo
    Possible solutions: class, state
    
    * Try:
    Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':XXX:taskTree'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
    at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
    at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
    at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
    at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
    at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
    at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
    at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
    at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
    at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:273)
    at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:258)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    Caused by: groovy.lang.MissingPropertyException: No such property: task for class: org.gradle.api.internal.artifacts.transform.TransformInfo$ChainedTransformInfo
    Possible solutions: class, state
    at com.dorongold.gradle.tasktree.TaskTreeTask$_render_closure4.doCall(TaskTreeTask.groovy:100)
    at com.sun.proxy.$Proxy119.execute(Unknown Source)
    at org.gradle.internal.graph.GraphRenderer.visit(GraphRenderer.java:41)
    at com.dorongold.gradle.tasktree.TaskTreeTask.render(TaskTreeTask.groovy:97)
    at com.dorongold.gradle.tasktree.TaskTreeTask$_render_closure5.doCall(TaskTreeTask.groovy:107)
    at com.dorongold.gradle.tasktree.TaskTreeTask.render(TaskTreeTask.groovy:106)
    at com.dorongold.gradle.tasktree.TaskTreeTask$_render_closure5.doCall(TaskTreeTask.groovy:107)
    at com.dorongold.gradle.tasktree.TaskTreeTask.render(TaskTreeTask.groovy:106)
    at com.dorongold.gradle.tasktree.TaskTreeTask$_render_closure5.doCall(TaskTreeTask.groovy:107)
    at com.dorongold.gradle.tasktree.TaskTreeTask.render(TaskTreeTask.groovy:106)
    at com.dorongold.gradle.tasktree.TaskTreeTask$_generate_closure3.doCall(TaskTreeTask.groovy:51)
    at com.dorongold.gradle.tasktree.TaskTreeTask.generate(TaskTreeTask.groovy:50)
    at org.gradle.api.tasks.diagnostics.AbstractReportTask$2.generateReport(AbstractReportTask.java:75)
    at org.gradle.api.tasks.diagnostics.internal.ReportGenerator.generateReport(ReportGenerator.java:58)
    at org.gradle.api.tasks.diagnostics.AbstractReportTask.generate(AbstractReportTask.java:85)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
    at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
    at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
    at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:786)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:753)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
    at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
    ... 31 more
    
    
    * Get more help at https://help.gradle.org

**Comment by davidburstromspotify** [comment]
Seeing the same thing. I think this is because of Android Gradle Plugin 3.3.

**Comment by ovitrif** [comment]
No fix or suggestions? Blocking me too

**Comment by NicholasVook** [comment]
No fix or suggestions? Blocking me too

**Comment by molokoka** [comment]
We have the same problem.

**Comment by nagraj-ec** [comment]
same problem here as well

**Comment by dorongold** [comment]
This is solved in the latest plugin version, which is now available on Gradle Portal.
Please use gradle-task-tree version 1.4.

**Comment by davidburstromspotify** [comment]
Thank you, works like a charm!
